# wrangler.toml
name = "honor-sales-worker"
main = "src/index.ts"
compatibility_date = "2024-05-15"

# Binding برای اتصال به D1 (پایگاه داده فروش)
[[d1_databases]]
binding = "honor_sales_db"
database_name = "honor_sales_db" 
database_id = "YOUR_DATABASE_ID_HERE"  # این را با ID واقعی جایگزین کن

# تعریف ارتباط Worker با Durable Object
[[durable_objects.bindings]]
name = "IMEI_MANAGER" 
class_name = "IMEI_Manager" 

# --- بخش حیاتی: ثبت Durable Object ---
[[migrations]]
tag = "v1-initial-do"
new_sqlite_classes = ["IMEI_Manager"]  # خطای 10097 را برطرف می کند