# wrangler.toml
name = "honor-sales-worker"
main = "src/index.ts"
compatibility_date = "2024-05-15"

# Binding برای اتصال به D1 (پایگاه داده فروش)
[[d1_databases]]
binding = "DB"
database_name = "honor_sales_db" 
database_id = "92efaa3a-c967-4131-9aca-be589a41a6f2"

# تعریف ارتباط Worker با Durable Object
[[durable_objects.bindings]]
name = "IMEI_MANAGER" 
class_name = "IMEI_Manager" 

# wrangler.toml

# ... بقیه کد در اینجا ...

# --- بخش حیاتی: ثبت Durable Object (تغییر یافته برای پلن رایگان) ---
[[migrations]]
tag = "v1-initial-do" 
# به جای new_classes از new_sqlite_classes استفاده می کنیم (به دلیل محدودیت پلن رایگان)
new_sqlite_classes = ["IMEI_Manager"] 
# new_classes = ["IMEI_Manager"] <--- این خط باید حذف شود
